# Generated by Django 4.1 on 2022-08-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_issue_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_views',
            field=models.IntegerField(default=0),
        ),
    ]
