# Generated by Django 4.1 on 2022-08-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_alter_section_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_views',
            field=models.IntegerField(),
        ),
    ]
