# Generated by Django 4.1 on 2022-09-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0010_remove_feedback_email_remove_feedback_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cover',
            field=models.ImageField(blank=True, upload_to='issues/%Y/%m/%d'),
        ),
    ]
