# Generated by Django 4.1 on 2022-10-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_action_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.CharField(default='general', max_length=255),
            preserve_default=False,
        ),
    ]
