# Generated by Django 4.1 on 2022-10-05 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_save',
            field=models.ManyToManyField(blank=True, related_name='posts_saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
