# Generated by Django 4.1 on 2022-10-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_bookmark_post_alter_bookmark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_save',
        ),
    ]
