# Generated by Django 4.1 on 2022-11-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='BlogComment',
            new_name='comment',
        ),
    ]
