# Generated by Django 4.1 on 2022-09-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('mobile', 'Draft'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('desktop', 'Desktop'), ('other', 'Other')], default='mobile', max_length=50),
            preserve_default=False,
        ),
    ]
