# Generated by Django 4.1 on 2022-09-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
