# Generated by Django 4.1 on 2022-09-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_product_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('desktop', 'Desktop'), ('other', 'Other')], max_length=50),
        ),
    ]
