# Generated by Django 4.1 on 2022-09-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_product_series_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='remarks',
            field=models.TextField(default='Good One'),
            preserve_default=False,
        ),
    ]
