# Generated by Django 4.1 on 2022-09-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_review_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalinfo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_info', to='devices.product'),
        ),
        migrations.AlterField(
            model_name='softwareinfo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='software_info', to='devices.product'),
        ),
    ]
