# Generated by Django 4.1 on 2022-09-02 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareinfo',
            old_name='os_type',
            new_name='os_ui',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='devices/%Y/%m/%d')),
                ('cover', models.BooleanField(default=False)),
                ('added', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='devices.product')),
            ],
            options={
                'ordering': ('added',),
            },
        ),
    ]
