# Generated by Django 4.1 on 2022-09-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_rename_os_type_softwareinfo_os_ui_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='photo',
        ),
    ]
