# Generated by Django 4.1 on 2022-09-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_rename_image_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cover',
        ),
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, upload_to='devices/%Y/%m/%d'),
        ),
    ]
