# Generated by Django 4.1 on 2022-09-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_remove_image_cover_product_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, upload_to='device-covers/%Y/%m/%d'),
        ),
    ]
