# Generated by Django 4.1 on 2022-09-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_product_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='added',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='physicalinfo',
            name='added',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='softwareinfo',
            name='added',
            field=models.BooleanField(default=True),
        ),
    ]
