# Generated by Django 4.1 on 2022-11-26 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='theme_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='theme',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_theme', to='account.theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_current_theme', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
