# Generated by Django 4.1 on 2022-10-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
